### ISSUE TITLE
代码块显示问题

### ISSUE THREAD

**Issue by AprilYoLies** [blinkfox/hexo-theme-matery#107]
```
highlight:
  enable: false
  # line_number: true
  # auto_detect: true
  # tab_replace:

prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'tomorrow'
  line_number: true    # default false
  custom_css:
```

这是我博客的代码块高亮配置，也使用了`npm i -S hexo-prism-plugin` 指令安装了插件，但是代码块还是不能显示很好的效果。
