### ISSUE TITLE
不算子统计数据在手机端访问无法显示问题

### ISSUE THREAD

**Issue by yooongchun** [blinkfox/hexo-theme-matery#143]
您好！
我尝试将不算子统计数据添加到自定义区域，首先我配置中打开了不算子统计，当然，，也安装好了相应插件
```yml
busuanziStatistics:
  enable: true
  totalTraffic: true # 总访问量
  totalNumberOfvisitors: true # 总人次
```
我在主题文件的`layout/_partial/post-statis.ejs`文件中添加了以下代码：
```js
<!-- total traffic -->
<% if (theme.busuanziStatistics && theme.busuanziStatistics.enable) { %>
<div class="statis">
    <span class="count"><a href="javascript:void(0);" id="busuanzi_value_site_pv"></a></span>
    <span class="name">访问</span>
</div>
<% } %>

<!-- total visitor -->
<% if (theme.busuanziStatistics && theme.busuanziStatistics.enable) { %>
<div class="statis">
    <span class="count"><a href="javascript:void(0);" id="busuanzi_value_site_uv"></a></span>
    <span class="name">访客</span>
</div>
<% } %>
```

在桌面浏览器中中数据显示正常
![](https://yooongchun-blog-v2.oss-cn-beijing.aliyuncs.com/201908/1.png)
但是当浏览器内宽度约小于991时却无法显示数据。
请问这是在代码中做了限制是吗？哪里可以修改呢？
望解答，谢谢！
