### ISSUE TITLE
你好，文章页面的宽度可以调整吗？怎么调整？有些图片比较大，加载出来放不下。

### ISSUE THREAD

**Issue by Zhengchaoqiang** [blinkfox/hexo-theme-matery#145]

**Comment by blinkfox** [comment]
要调整的话，肯定是可以调的，需要你自己修改些 `CSS` 样式才行。

在 `matery.css` 文件中，找到如下样式（在约 `18` 行的位置），然后修改 `post-container` 中的最大宽度 `max-width` 的值即可：

```css
@media only screen and (min-width: 993px) {
    .container {
        width: 85%;
        max-width: 1125px;
    }
    .post-container {
        width: 90%;
        margin: 0 auto;
        max-width: 1250px;
    }

}
```
