### ISSUE TITLE
手机端，header不能自动适配屏幕大小，有错位

### ISSUE THREAD

**Issue by onloner2012** [blinkfox/hexo-theme-matery#147]
![微信图片编辑_20190901125434](https://user-images.githubusercontent.com/15322258/64071947-63af6a80-ccb8-11e9-9b0e-7752eca5bfdc.jpg)
问题如图:smile:

**Comment by blinkfox** [comment]
可以自己修改大标题在手机端的显示样式，在主题文件的 `source/css/my.css` 文件中，新增下面这样的 `CSS` 代码，修改成自己喜欢的字体大小即可：

```css
@media only screen and (max-width: 601px) {
    .bg-cover .title {
        font-size: 2.8rem;
    }
}
```

**Comment by EscapeLife** [comment]
@blinkfox 添加了一下，测试没有什么效果。`font-size`改动之后，更新网站，字体还是`28px`大小。

**Comment by blinkfox** [comment]
@EscapeLife 把你的地址给我看一下

**Comment by onloner2012** [comment]
> 可以自己修改大标题在手机端的显示样式，在主题文件的 `source/css/my.css` 文件中，新增下面这样的 `CSS` 代码，修改成自己喜欢的字体大小即可：
> 
> ```css
> @media only screen and (max-width: 601px) {
>     .bg-cover .title {
>         font-size: 2.8rem;
>     }
> }
> ```

感谢大佬的回复，已经修改了span的rem，数值为1rem

**Comment by EscapeLife** [comment]
> @EscapeLife 把你的地址给我看一下

@blinkfox 麻烦看下，对应下面👇地址：

- https://escapelife.github.io/

![image](https://user-images.githubusercontent.com/16237571/64240566-af6e4800-cf34-11e9-82f1-47ddb73f6fdf.png)

**Comment by blinkfox** [comment]
@EscapeLife 我看了下，是生效的啊，手机端字变小了的

**Comment by EscapeLife** [comment]
> @EscapeLife 我看了下，是生效的啊，手机端字变小了的

- 我这里，我自己看还是没有变小。后来我改了，title的选择器，如下所示：

```css
@media only screen and (max-width: 601px) {
    header .brand-logo .logo-span {
        font-size: 1.5rem;
    }
}
```

- 我通过电脑模拟手机尺寸，使用了`header .brand-logo .logo-span`，之后就好了。

![image](https://user-images.githubusercontent.com/16237571/64317925-86f55500-cfeb-11e9-88d5-19e1676118f2.png)
