### ISSUE TITLE
[Bug] 更新之后文章链接无法点击

### ISSUE THREAD

**Issue by EscapeLife** [blinkfox/hexo-theme-matery#159]
- 在博客主页无法点击对应文档，进入页面里面。只能够过搜索框才可以进入。

![image](https://user-images.githubusercontent.com/16237571/64939435-85e9e080-d893-11e9-921f-bee53483b8c3.png)

**Comment by EscapeLife** [comment]
- 提交的commit记录
- `https://github.com/blinkfox/hexo-theme-matery/commit/1ba754e90cab1da576d72816ed035aa9457e1f01`

**Comment by EscapeLife** [comment]
@blinkfox @L1cardo 麻烦有时间了看看୧(๑•̀◡•́๑)૭

**Comment by L1cardo** [comment]
你的博客地址多少，我看看

**Comment by L1cardo** [comment]
可以啊。要点击文章的图片，下面的文章的简要点不动。我不知道以前能不能点动，不知道是不是这次更新引起的。

**Comment by blinkfox** [comment]
@EscapeLife @L1cardo 博客地址应该是这个吧 [https://escapelife.github.io/](https://escapelife.github.io/)，我看是一个全局的 `canvas` 遮挡了引起的，这个 `canvas` 还被置于了最顶层。

**Comment by L1cardo** [comment]
@EscapeLife 仔细看配置，是不是这个引起的？  设置为1就可以了
![截屏2019-09-16下午5 27 02](https://user-images.githubusercontent.com/33802186/64947401-78d6ec80-d8a7-11e9-857e-f3a4c5cf212b.png)

**Comment by EscapeLife** [comment]
@L1cardo @blinkfox 下午比较忙，没有及时看到。我明天早上去了，试试看。感谢两位👍

**Comment by L1cardo** [comment]
@EscapeLife 要是解决了，那就把这个issue关了啊

**Comment by blinkfox** [comment]
我更新了最新的主题看了下，默认确实是有这个问题的。

**Comment by EscapeLife** [comment]
@blinkfox @L1cardo 确实是下面这个配置引起的，设置为`1`就可以了，麻烦两个有时间提交下吧。

```yaml
#背景canvas-nest
canvas_nest:
  enable: true
  color: 0,0,255 #线条颜色, 默认: '0,0,0' ；三个数字分别为(R,G,B)，注意用,分割
  pointColor: 0,0,255 #交点颜色, 默认: '0,0,0' ；三个数字分别为(R,G,B)，注意用,分割
  opacity: 0.7 # 线条透明度（0~1）, 默认: 0.5
  zIndex: 1 # 背景的z-index属性，css属性用于控制所在层的位置, 默认: -1
  count: 99 # 线条的总数量, 默认: 99
```
