### ISSUE TITLE
开启了目录功能后显示问题

### ISSUE THREAD

**Issue by ixsim** [blinkfox/hexo-theme-matery#21]
开启了文章TOC功能后。
目录是不是有指定的区域啊。正常显示了几行后，后面的样式没了。

 标题 很多的文章 ，生成的目录就有问题。
如何更改目录区域大小。
或者能不能把目录区域做成可滚动式的？

**Comment by ixsim** [comment]
之前提交的两个issue麻烦关闭了。是我自己操作错误。

**Comment by blinkfox** [comment]
嗯,TOC的太长了，是有些问题，后续有空会考虑做成折叠的功能或者仅显示三到四个层级的标题即可。

**Comment by blinkfox** [comment]
@ixsim TOC目录的一些问题已经修复了，TOC目录随着滚动可自动折叠和展开，TOC目录也可以在主题的`_config.yml`文件中配置显示目录的标题范围，默认是`h2, h3, h4`。

@scutem TOC目录的链接用的是锚点，浏览器默认就是在顶上的，要改成居中的话，`CSS`是不行的。如果你想居中的话，倒是可以自己稍微改些样式，让标题偏离顶部一定的距离来实现，修改主题文件中`/layout/_partial/post-detail-toc.ejs`中`padding-top`和`margin-top`的值,用来偏离顶部的距离，比如：

```css
#articleContent h1,
#articleContent h2,
#articleContent h3,
#articleContent h4,
#articleContent h5,
#articleContent h6 {
    padding-top: 300px;
    margin-top: -300px;
}
```
