### ISSUE TITLE
目录能否支持下滑动?现在目录过长就看不到下面，没法下滑

### ISSUE THREAD

**Issue by CodeGeekLee** [blinkfox/hexo-theme-matery#234]

**Comment by blinkfox** [comment]
没啥好的方式，只能给目录做滚动条才行，但怕比较难看。

**Comment by 202252197** [comment]
怎末过滑动条 @blinkfox

**Comment by VanLiuZhi** [comment]
这个应该做上去的，我目录长的显示错误了

**Comment by 202252197** [comment]
大哥建议搞一个合适的滚动条我太难了,我的笔记现在只能分成5份文件 @blinkfox

**Comment by blinkfox** [comment]
更新 dev 试试，或者在 `post-detail-toc.ejs` 文件中添加如下样式，TOC 就有滚动条了。

```css
#toc-content {
    height: calc(100vh - 250px);
    overflow: scroll;
}
```
