### ISSUE TITLE
大佬们好，请问右侧生成的目录怎么才能显示编号

### ISSUE THREAD

**Issue by chengpengzhao** [blinkfox/hexo-theme-matery#252]
我往`post-detail-toc.ejs`里改了段能让post自动编号的内容：
```css
#articleContent h1 {
	counter-increment: counter_h1;
	counter-reset: counter_h2;
}
#articleContent h1:before {
	content: counter(counter_h1)"　";
}

#articleContent h2 {
	counter-increment: counter_h2;
	counter-reset: counter_h3;
}
#articleContent h2:before {
	content: counter(counter_h1)"."counter(counter_h2)"　";
}

#articleContent h3 {
	counter-increment: counter_h3;
	counter-reset: counter_h4;
}
#articleContent h3:before {
	content: counter(counter_h1)"."counter(counter_h2)"."counter(counter_h3)"　";
}
```

但因为这个编号的属性是 ::before  ， 在右侧目录栏里显示不出来；而且右侧目录栏相关的`post-detail-toc.ejs`代码我也看不太懂，因为没学过这方面语法。
求助~~~现在的[效果](https://chengpengzhao.com/2019/11/20/2019-11-20-cong-hugo-zhe-teng-dao-hexo-guo-cheng-ji-lu/) 就只能这样了。
