### ISSUE TITLE
音乐播放器开启吸底模式后，页面中央会留下空白

### ISSUE THREAD

**Issue by BrambleXu** [blinkfox/hexo-theme-matery#256]
不开启的时候

![image](https://user-images.githubusercontent.com/10768193/69697564-237c4e80-1126-11ea-8046-2b3d469a2a45.png)

开启吸底模式的配置
```
music:
  enable: true
  showTitle: false
  title: 听听音乐
  fixed: true # 开启吸底模式
  autoplay: true # 是否自动播放
  theme: '#542674'
  loop: 'all' # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'list' # 音频循环顺序, 可选值: 'list', 'random'
  preload: 'auto' # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.5 # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: false # 列表默认折叠
  listMaxHeight: #列表最大高度
```
下面中央白色的框就是原本播放器所在的位置。能不能设置在开启吸底模式后，隐藏这个部分呢

![image](https://user-images.githubusercontent.com/10768193/69697398-a3ee7f80-1125-11ea-9202-9d9260af8975.png)
