### ISSUE TITLE
希望能添加控制TOC展开所有层级标题的设置

### ISSUE THREAD

**Issue by BrambleXu** [blinkfox/hexo-theme-matery#258]
现在侧边栏的TOC默认只能看到第一层级，只有页面下移到对应的层级后，才会展开第下一层级。能不能在`_config.yml`里添加一个toc的设置，当`folding: false`时，展开所有层级

**Comment by BrambleXu** [comment]
```
toc:
  enable: true
  heading: h2, h3, h4
  showToggleBtn: true # 是否显示切换TOC目录展开收缩的按钮
  folding: ture # 默认折叠所有层级
```

效果图

![image](https://user-images.githubusercontent.com/10768193/69781993-2133f600-11f3-11ea-9d5a-bc3fa7961f2e.png)
