### ISSUE TITLE
建议默认配置里关闭背景动态彩带减少CPU占用率 + 如何配置能减少CPU占用率

### ISSUE THREAD

**Issue by BrambleXu** [blinkfox/hexo-theme-matery#271]
# 1 建议默认配置里关闭背景动态彩带减少CPU占用率

背景动态彩带效果占用的CPU资源太多了，建议在`_config.yml`里关闭。对应的可以开启静止彩带效果，这个不怎么占用CPU资源。

```
# 背景静止彩带.
ribbon:
  enable: true 
  ......

# 背景动态彩带.
ribbon_dynamic:
  enable: false
```

----

测试站点：https://bramblexu.org/

开启背景动态彩带后，在两个浏览器里分别访问网页进行测试。Chrome和Safari的CPU占用率提升了40-50%。而且Safafi还会有下面的警告：

![](https://raw.githubusercontent.com/LearnXu/images/master/imgs/20191204222722.png)

所以还是关闭比较好

----

# 2 如何配置能减少CPU占用率

不过即使关闭动态彩带，单独打开博客主页，CPU占用率也会有20~30%。想请教一下如何更改配置文件可以减少CPU占用率
