### ISSUE TITLE
[bug] click_to_change即使设置为了false，还是会在点击的时候更换彩带

### ISSUE THREAD

**Issue by BrambleXu** [blinkfox/hexo-theme-matery#272]
click_to_change即使设置为了false，还是会在点击的时候更换彩带

```
# 背景静止彩带.
ribbon:
  enable: true
  size: 150 # 彩带大小, 默认: 90.
  alpha: 0.6 # 彩带透明度 (0 ~ 1), 默认: 0.6.
  zIndex: -1 # 背景的z-index属性，css属性用于控制所在层的位置, 默认: -1.
  click_to_change: false  # 设置是否每次点击都更换彩带.
```
