### ISSUE TITLE
RSS订阅无法查看整篇文章

### ISSUE THREAD

**Issue by BrambleXu** [blinkfox/hexo-theme-matery#274]
我使用feedly订阅自己博客后，发现无法查看整篇文章的内容

![IMG_1143](https://user-images.githubusercontent.com/10768193/70369646-2a624880-1900-11ea-9bdb-769bd204fc44.PNG)

查看其他订阅的文章没有这个问题

![IMG_1142](https://user-images.githubusercontent.com/10768193/70369651-34844700-1900-11ea-98b7-6e6db940ac63.PNG)

**Comment by chengpengzhao** [comment]
我也想知道具体原因是什么，不过我试了下把atom改成rss2就行了。这是我的根目录_config.yml
```yml
feed: 
  type: rss2 
  path: rss2.xml 
  limit: false 
  hub: 
  content: true
  content_limit: 140 
  content_limit_delim: '...' 
  order_by: -date
```

具体可参考`node_modules/hexo-generator-feed`文件夹里的说明
