### ISSUE TITLE
about页面是404怎么解决

### ISSUE THREAD

**Issue by jackfox58** [blinkfox/hexo-theme-matery#29]
404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

GitHub Status — @githubstatus

**Comment by blinkfox** [comment]
@jackfox58 
你应该没有新建`about`页吧，新建命令:

```bash
hexo new page "about"
```
然后，编辑你刚刚新建的页面文件`/source/about/index.md`，内容如下即可:

```yml
---
title: about
date: 2018-09-30 17:25:30
type: "about"
layout: "about"
---
```
