### ISSUE TITLE
主页的RSS订阅链接默认是atom.xml，更改为rss2.xml后无法自动更新链接

### ISSUE THREAD

**Issue by BrambleXu** [blinkfox/hexo-theme-matery#296]
```
feed:
  type: rss2
  path: rss2.xml
  limit: false
  content: true
  content_limit: 140
  content_limit_delim: '...'
  order_by: -date
```

当设置 rss为rss2类型的时候，主页的rss按钮对应的还是atom.xml，显示为[404](https://bramblexu.org/atom.xml)。

希望按照 feed type 更新rss button对应的链接：

![image](https://user-images.githubusercontent.com/10768193/72983918-c818c500-3e25-11ea-8e37-b70fa9577d3a.png)

RSS button有两个，一个在页面正中央，一个在页脚
