### ISSUE TITLE
分类中，雷达的统计层级被遮住了

### ISSUE THREAD

**Issue by mouyong** [blinkfox/hexo-theme-matery#301]
![image](https://user-images.githubusercontent.com/10336437/73411272-bc566280-433f-11ea-89cf-bfca30be5aa1.png)

**Comment by blinkfox** [comment]
已知晓，后续会修改，你要即时解决的化，在主题的 `source/css/matery.css` 文件中，第 `1291` 行的样式中，增加一个 `z-index: 0;` 的样式属性即可。代码如下：

```css
.chip-container .chip {
    margin: 10px 10px;
    padding: 19px 14px;
    display: inline-flex;
    line-height: 0;
    font-size: 1rem;
    font-weight: 500;
    border-radius: 5px;
    cursor: pointer;
    box-shadow: 0 3px 5px rgba(0, 0, 0, .12);
    z-index: 0;
}
```
