### ISSUE TITLE
标题左上角的 logo 和 title 垂直方向上有点偏下

### ISSUE THREAD

**Issue by rxliuli** [blinkfox/hexo-theme-matery#307]
![image](https://user-images.githubusercontent.com/24560368/73714816-ffa03f00-474c-11ea-97ca-aefc07b6852c.png)

去看了一下是因为 `.waves-effect` 添加的垂直居中样式

![image](https://user-images.githubusercontent.com/24560368/73714856-16df2c80-474d-11ea-97aa-56dee4a2b2fe.png)

修改为 `vertical-align: top;` 就正常了

![image](https://user-images.githubusercontent.com/24560368/73714914-40985380-474d-11ea-9a5c-79d000a9b0d6.png)

吾辈目前的处理方案是修改 `matery.css`，希望官方修复一下。。。

```css
/*hack 修改顶部 logo 的文字垂直对齐为 top，避免默认 middle 看起来偏下*/
header .brand-logo .waves-effect {
    vertical-align: top;
}
```
