### ISSUE TITLE
关于  `文章字数统计插件`一个bug

### ISSUE THREAD

**Issue by makingBug** [blinkfox/hexo-theme-matery#326]
按照框架说明文件的要求：更改 theme下的配置文件`_config.yml`如下：
```
postInfo:
  date: true
  update: false
  wordCount: false # 设置文章字数统计为 true.
  totalCount: false # 设置站点文章总字数统计为 true.
  min2read: false # 阅读时长.
  readCount: false # 阅读次数.
```
在本地运行后出现如下错误
![image](https://user-images.githubusercontent.com/41457449/74511196-6ccb8580-4f40-11ea-8172-9090b8b58a97.png)

这里应该是配置文件和源代码中变量不匹配出现了问题，将配置文件中的`totalCount`改为`totalcount`，将`wordCount`改为`wordcount`即可，目前没有出现bug，不知道后面会不会有bug。
