### ISSUE TITLE
音乐播放器有个bug

### ISSUE THREAD

**Issue by meteorsh** [blinkfox/hexo-theme-matery#327]
![image](https://user-images.githubusercontent.com/46078304/74513334-4d832700-4f45-11ea-9b39-1bf061ca1356.png)
我在配置的是否发现这里有个❎，请问要怎么去掉？
```
我的yml设置是这样的
# Whether to display the musics.
# 是否在首页显示音乐.
music:
  enable: true
  title: #非吸底模式有效
    enable: true
    show: 听听音乐
  server: netease   #require	music platform: netease, tencent, kugou, xiami, baidu
  type: playlist	#require song, playlist, album, search, artist
  id: 503838841     #require	song id / playlist id / album id / search keyword
  fixed: false      # 开启吸底模式，就是左下角的吸盘
  autoplay: false   # 是否自动播放
  theme: '#42b983'
  loop: 'all'       # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'random'   # 音频循环顺序, 可选值: 'list', 'random'
  preload: 'auto'   # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7       # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: false  # 列表默认折叠
```
