### ISSUE TITLE
代码区的水平滚动条鼠标拖拽不了

### ISSUE THREAD

**Issue by chunchengwei** [blinkfox/hexo-theme-matery#34]
代码块，在手机显示上没有问题，但在电脑上显示时，用鼠标拖拽水平滚动条拖拽不了。

**Comment by blinkfox** [comment]
@chunchengwei 并没有发现你说的问题呢

**Comment by chunchengwei** [comment]
@blinkfox 在谷歌浏览器下没问题，但是在safari下就拖拽不了了

**Comment by blinkfox** [comment]
`safari`下的一个效果，它本来就是这样的。

**Comment by chunchengwei** [comment]
> `safari`下的一个效果，它本来就是这样的。

可以同时也添加水平拖拽的功能么？平时用鼠标，不能拖拽很不方便。

**Comment by blinkfox** [comment]
这个程序没啥问题，是`safari`浏览器的特殊功能，你可以去Mac设置项里面修改成“始终显示滚动条”的功能。具体方法你可以用搜索引擎搜一下。

**Comment by chunchengwei** [comment]
![image](https://user-images.githubusercontent.com/15673819/49505915-b38f0b80-f8b7-11e8-9e8f-ef92dc790747.png)

可以显示出来滚动条，但是拖拽不了。而且已经打开了始终显示滚动条

**Comment by blinkfox** [comment]
那就没法了，`safari`这样搞的吧，那只能让代码折行，不出现滚动条就行了，你到`matery.css`文件中约`124`行的样式里面，加上一行`white-space: pre-wrap !important;`的折行样式即可，代码如下：

```css
code[class*="language-"],
pre[class*="language-"] {
    color: #e8eaf6;
    white-space: pre-wrap !important;
}
```
