### ISSUE TITLE
toc目录before定位错误

### ISSUE THREAD

**Issue by lzctuhao** [blinkfox/hexo-theme-matery#385]
目前，好像所有使用该主题的站点都出现了该问题：
在带有toc的页面下，当`toc`还是`position: absolute`(即不滚动页面)时，激活的toc标题的左侧竖线（`::before`伪元素）会跑到最左边。
见图：
![](https://s1.ax1x.com/2020/03/24/8qcdkF.jpg)

我自己的解决方法：
更改样式为：

```css
.toc-link::before {
    background-color: var(--bgcolor);
    content: ' ';
    display: block;
    height: inherit;
    margin-top: 1px;
    position: absolute;
    width: 2px;
    right: 23.5vw;
}
```

**Comment by blinkfox** [comment]
嗯，以前都没注意到这个，我试了下，你这个也不行。

**Comment by lzctuhao** [comment]
抱歉，复制错了。。。
应该是这个：
```css
.toc-link::before {
    margin-top: 5px;
    position: absolute;
    right: 23.5vw;
    display: block;
}
.toc-fixed .toc-link::before{
  position: fixed!important;/*当toc的位置改为fixed时，.toc-link::before也要改为fixed*/
}
```
然后要把`libs/tocbot/tocbot.css`里面`.toc-link::before`的`left: 0;`删掉，
因为如果同时存在left和right，会先识别left。

亲测成功哦~
