### ISSUE TITLE
Daovioce 与 返回顶部按钮重合

### ISSUE THREAD

**Issue by Cherrison** [blinkfox/hexo-theme-matery#402]
![image](https://user-images.githubusercontent.com/42861256/78535909-804bec00-781f-11ea-90c6-a1b9e8e6625b.png)

**Comment by Cherrison** [comment]
## 希望可以弄成这个样子, 可以源文件 没法修改 
找不到, 试过更改了,
将那个vue打包的js文件, 找出来修改, 然后 在layout.ejs 修改了 daovoice的 url 为自己服务器上修改的 js 文件
可是这个属性太多 没法确定是改什么地方, 试了几次, 没有成功!

![2020-04-06 16-27-31 的屏幕截图](https://user-images.githubusercontent.com/42861256/78541507-4fbc8000-7828-11ea-91b1-a3c036402903.png)

**Comment by blinkfox** [comment]
我没弄过 `DaoVioce` 的，你加这两个样式试试呢？

```css
#daodream-container .daodream-launcher-enabled {
    bottom: 140px !important;
    right: 17px !important;
}
```
