### ISSUE TITLE
关于主题颜色的问题

### ISSUE THREAD

**Issue by TLHorse** [blinkfox/hexo-theme-matery#418]
matery中，主题颜色（例如导航栏和footer、标签等）是草绿色。怎样改成别的颜色？觉得草绿色太亮眼，很xx。
可不可以修改ejs？找了半天没找到颜色定义。

**Comment by TLHorse** [comment]
没人回吗？

**Comment by TLHorse** [comment]
会了，设置
```css
.bg-color {
    background-image: linear-gradient(to right, #0F2027 0%, #203A43 60%, #0f9d58 100%);
}
```
就可以了
