### ISSUE TITLE
升级1.3后如何不显示歌词

### ISSUE THREAD

**Issue by BrambleXu** [blinkfox/hexo-theme-matery#468]
播放器的默认设置会显示歌词：

![image](https://user-images.githubusercontent.com/10768193/83347201-4fd78880-a35e-11ea-889b-3c0ac6e7612d.png)

我尝试设置了`lrcType: 0` ，但是不起作用。
```
music:
  enable: true
  title: #非吸底模式有效
    enable: true
    show: 听听音乐
  autoHide: true    # hide automaticaly
  server: netease   #require	music platform: netease, tencent, kugou, xiami, baidu
  type: playlist    #require song, playlist, album, search, artist
  id: 42168718      #require	song id / playlist id / album id / search keyword
  fixed: true       # 开启吸底模式
  autoplay: false   # 是否自动播放
  theme: '#542674'
  loop: 'all'       # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'random'   # 音频循环顺序, 可选值: 'list', 'random'
  preload: 'none'   # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.5       # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: true  # 列表默认折叠
  lrcType: 0        # 不显示歌词
```
