### ISSUE TITLE
Navigation texts didn't get translated

### ISSUE THREAD

**Issue by lupa18** [blinkfox/hexo-theme-matery#480]
Hello, and thanks for your work. 

I had set up several languages and changed default language.
Then I added some .yml files to language folder. Lot of texts got translated but nav texts don't change. Ie: Index, Tags, Categories, etc.. stay in English. 

thanks again

**Comment by blinkfox** [comment]
@lupa18 Navigation text is written on the theme `_config.yml`  file, you can change it to any text you want.

**Comment by lupa18** [comment]
Hello @blinkfox !
As I can see, it's actually configured in navigation.ejs Both languages seems to be configured there, hard coded. 

Then, in languages/default.yml text keys are available. 

Maybe some could be changed there to call text keys from land yml and got multi-language working?

**Comment by blinkfox** [comment]
@lupa18 The design purpose of the navigation menu at the time was to allow users to customize the menu name, so instead of reading the text in `languages`, the user was allowed to set the menu name in `_config.yml`, the following is my custom Menu name:

```yaml
menu:
  My Index:
    url: /
    icon: fas fa-home
  My Tags:
    url: /tags
    icon: fas fa-tags
  My Categories:
    url: /categories
    icon: fas fa-bookmark
  My Archives:
    url: /archives
    icon: fas fa-archive
  关于我们:
    url: /about
    icon: fas fa-user-circle
  联系我们:
    url: /contact
    icon: fas fa-comments
  Friends Link:
    url: /friends
    icon: fas fa-address-book
```
