### ISSUE TITLE
如何新增一项博文的修改日期？

### ISSUE THREAD

**Issue by KennyNg-19** [blinkfox/hexo-theme-matery#497]
现在只有发布日期

**Comment by blinkfox** [comment]
目前没有这一项的定义和现实。

**Comment by BrambleXu** [comment]
@KennyNg-19 

设置update为true可以显示更新时间，下面是我的配置：
```
postInfo:
  date: true # 发布日期
  update: true # 更新日期
  wordCount: true # 文章字数统计
  totalCount: true # 站点总文章字数
  min2read: true # 文章阅读时长
  readCount: true # 文章阅读次
```
效果可以看[这篇文章](https://bramblexu.com/posts/e99c5907/)
