### ISSUE TITLE
文章描述

### ISSUE THREAD

**Issue by Loveslife** [blinkfox/hexo-theme-matery#51]
你好，请问现在有没有办法让卡片中的文字显示为自定义的内容。
![image](https://user-images.githubusercontent.com/23011675/51430971-8a56ee80-1c5d-11e9-9dbd-ef4445843d1e.png)

**Comment by blinkfox** [comment]
目前来看不行，只能自己改代码了，后续版本添加这个功能吧

**Comment by blinkfox** [comment]
先不关这个问题吧，后续实现完了再关。

**Comment by blinkfox** [comment]
@Loveslife 这个功能我已经加上了，更新最新的主题即可。你可以在文章的`Front-matter`中自定义文章内容的摘要`summary`，写法如下：

```yaml
---
title: typora-vue-theme主题介绍
date: 2018-09-07 09:25:00
img: /source/images/xxx.jpg
summary: 这是你自定义的文章摘要内容，如果这个属性有值，文章卡片摘要就显示这段文字，否则程序会自动截取文章的部分内容作为摘要
categories: Markdown
tags:
  - Typora
  - Markdown
---
```
