### ISSUE TITLE
安装hexo-helper-quiz后选择题选项无法点击选项

### ISSUE THREAD

**Issue by shj37** [blinkfox/hexo-theme-matery#553]
![hexo_quiz](https://user-images.githubusercontent.com/8279674/97460281-9665f900-1977-11eb-9207-ccede060418a.png)

应该显示右边的图，实际显示不出选项的标记（左边）。一点就只能点出那些小"心"，谢谢

尝试过：把clicklove关掉也不行
发现只要是 input radio 就不显示

我猜是css设置或JS冲突问题，但是实在没办法了

**Comment by shj37** [comment]
尝试把clicklove关掉也不行，我猜是css设置问题，但是实在没办法了

**Comment by blinkfox** [comment]
可能是样式冲突了

**Comment by shj37** [comment]
> 可能是样式冲突了

有解决方案或建议吗？

**Comment by blinkfox** [comment]
@shj37 没装过这个，不想花精力去试这个了

**Comment by shj37** [comment]
> @shj37 没装过这个，不想花精力去试这个了

那能不能大体猜一下是哪个样式文件里的哪个样式可能有冲突？谢谢

**Comment by blinkfox** [comment]
@shj37 你有线上的页面吗？发我看看

**Comment by shj37** [comment]
> @shj37 你有线上的页面吗？发我看看

@blinkfox 
https://eduunited.org/2020/02/20/hello-world/ 谢谢

**Comment by blinkfox** [comment]
@shj37 我看了下，主要原因是 `materialize.min.css` 的 css 框架中把 `redio` 和 checkbox 给隐藏了，你把透明度设置成1就行。可以在 css 文件中加下面样式：

```css
.__quiz__ [type="radio"]:not(:checked), [type="radio"]:checked,
.__quiz__ [type="checkbox"]:not(:checked), [type="checkbox"]:checked {
    opacity: 1;
}
```

其它的一些单选，复选框的位置样式，你就自己调一下了
