### ISSUE TITLE
按照文档，_config.yml里配置了music。但实际上没生效

### ISSUE THREAD

**Issue by fineday009** [blinkfox/hexo-theme-matery#606]
![image](https://user-images.githubusercontent.com/8936328/103179285-6ed2d480-48c5-11eb-8c14-aad341924900.png)
```
# Whether to display the music
music:
  enable: true
  title: 		   # non-fixed mode works
    enable: true
    show: Listen to music
  server: netease   # require music platform: netease, tencent, kugou, xiami, baidu
  type: song    # require song, playlist, album, search, artist
  id: 95796     # require song id / playlist id / album id / search keyword
  fixed: false      # enable fixed mode
  autoplay: false   # audio atuoplay
  theme: '#42b983'
  loop: 'all'       # player loop play, values: 'all', 'one', 'none'
  order: 'random'   # player play order, values: 'list', 'random'
  preload: 'auto'   # values: 'none', 'metadata', 'auto'
  volume: 0.7       # default volume, notice that player will remember user setting, default volume will not work after user set volume themselves
  listFolded: false  # indicate whether list should folded at first
```
**只配置了一首歌，但首页拉出来的歌单是一个列表，都是不认识的歌。什么情况？**

![image](https://user-images.githubusercontent.com/8936328/103179314-b22d4300-48c5-11eb-9735-43025c5313f7.png)
