### ISSUE TITLE
首页图片轮播设置

### ISSUE THREAD

**Issue by dikhin** [blinkfox/hexo-theme-matery#646]
你好，想请教一下如何设置首页封面数张图片轮播？现在首页只显示一张变色后banner图片
我的设置如下：
```
cover:
  showPrevNext: true # 是否显示左右切换按钮. Whether to display the left and right toggle buttons.
  showIndicators: true # 是否显示指示器. # Whether to display the indicators
  autoLoop: true # 是否自动轮播. Whether it is automatically rotated.
  duration: 120 # 切换延迟时间. Switching delay time.
  intervalTime: 5000 # 自动切换下一张的间隔时间. Automatically switch the interval of the next one.
  useConfig: false # 是否使用配置文件, 在 _data/covers.json 下配置推荐文章, false则使用主题在文章中的配置 cover coverImg

banner:
  enable: false
```

谢谢！
