### ISSUE TITLE
首页无法添加视频

### ISSUE THREAD

**Issue by mendax1234** [blinkfox/hexo-theme-matery#674]
下面是我theme—config里关于视频的部分
```
# Whether to display the videos.
# 是否在首页显示视频.
video:
  enable: true
  showTitle: true
  title: 2021 Recap
  url: https://www.iqiyi.com/v_23805y8jn0g.html
  iframeUrl: #在bilibili或者爱奇艺分享时选择iframe，然后填那个url来这里，sample: //player.bilibili.com/player.html?aid=669520137&bvid=BV1oa4y1L7mw&cid=234543483&page=1
  pic:
  thumbnails:
  height: # 如：400
  autoplay: true # 是否自动播放
  theme: '#42b983'
  loop: true # 是否循环播放
  preload: 'auto' # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7
```
可是到网页上就显示视频加载失败，网站的域名是：https://team6940.github.io/
