### ISSUE TITLE
代码块全选问题，似乎是行号那边影响了内容

### ISSUE THREAD

**Issue by k0xx11** [blinkfox/hexo-theme-matery#696]
<img width="550" alt="matery代码块2" src="https://user-images.githubusercontent.com/54017627/132234678-074bcf6e-e04e-4fea-8174-d3d5e70b2e80.png">
<img width="523" alt="matery代码块" src="https://user-images.githubusercontent.com/54017627/132234685-788d2408-c387-4ea2-85e3-9546d41c3de9.png">

来个表哥看看，
My Blog is k0xx11.github.io

**Comment by HKMV** [comment]
师傅怎么解决的我也遇到了这个问题

**Comment by HKMV** [comment]
废了几个小时时间终于找到原因了.
``` css
pre[class*="language-"].line-numbers>code {
	position: sticky;  /* 原来是relative */
	white-space: inherit;
}
```
按照这样修改后即可正常显示

**Comment by Thysrael** [comment]
> 

请问这是在哪个文件里，我也遇到这个问题，但是在matery.css中找不到这些代码

**Comment by Ricky2333** [comment]
> 
解决方案：[[查看 #721 和 #637 的两个 commit 内容](https://github.com/blinkfox/hexo-theme-matery/pull/724)](https://github.com/blinkfox/hexo-theme-matery/pull/724) 按照这样改完可以显示行号，但是改完后的行号感觉没有对齐

**Comment by Ricky2333** [comment]
解决方案：[查看 #721 和 #637 的两个 commit 内容](https://github.com/blinkfox/hexo-theme-matery/pull/724)
按照这两个解决方案可以显示行号，但是行号不是很对齐，有一点点偏差

**Comment by Eished** [comment]
> > 
> 
> 请问这是在哪个文件里，我也遇到这个问题，但是在matery.css中找不到这些代码

`themes\hexo-theme-matery\source\libs\prism\prism.min.css`
```css
pre[class*=language-].line-numbers>code{position:relative;white-space:inherit}
```
