### ISSUE TITLE
请问为什么 menu 的部分，不用 language 设定呢？

### ISSUE THREAD

**Issue by oneheed** [blinkfox/hexo-theme-matery#699]
menuMap 被写死成 zh-CN 才有效， 请问为什么language 呢？

<%- __(key) %>

**Comment by rainbowtp** [comment]
2级菜单没有被翻译 怎样实现呢

**Comment by oneheed** [comment]
> 2级菜单没有被翻译 怎样实现呢

两个方法，挑一个做建议改`_config.yml`：
1. 改代码
mobile-nav.ejs
navigation.ejs

>加
>```
>menuMap.set("Medias", "媒体");
>menuMap.set("Musics", "音乐");
>```

>```
><span><%- childrenLink.name %></span>
>```
>改成下面
>```
><span><%- (config.language === 'zh-CN' && menuMap.has(childrenLink.name)) ? menuMap.get(childrenLink.name) : >childrenLink.name %></span>
>```
2. _config.yml 
```
  媒体:
    icon: fas fa-list
    children:
      - name: 音乐
        url: /musics
        icon: fas fa-music
      - name: 电影
        url: /movies
        icon: fas fa-film
```
