### ISSUE TITLE
代码块不显示行号(已按照指南进行过设置！！！)

### ISSUE THREAD

**Issue by xzajyjs** [blinkfox/hexo-theme-matery#705]
# 不显示代码块行号！！！
### 已经关闭自带的highlight，并添加了如下代码到主题的config
```
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'tomorrow'
  line_number: true   # default false
  custom_css:
```
代码块相关设置也已经修改
```
# 代码块相关
code:
  lang: true # 代码块是否显示名称
  copy: true # 代码块是否可复制
  shrink: true # 代码块是否可以收缩
  break: false # 代码是否折行
```
