### ISSUE TITLE
您好，我这里点击文章目录不能实现跳转

### ISSUE THREAD

**Issue by Yancey597** [blinkfox/hexo-theme-matery#712]
```yml
toc:
  enable: true
  heading: h1, h2, h3, h4
  collapseDepth: 0 # 目录默认展开层级
  showToggleBtn: true # 是否显示切换TOC目录展开收缩的按钮
```

这是我目前的toc配置，然后每篇文章的toc开关也开启了
