### ISSUE TITLE
Default covers.json lost in directory

### ISSUE THREAD

**Issue by kawhicurry** [blinkfox/hexo-theme-matery#760]
```yaml
cover:
  showPrevNext: ture # 是否显示左右切换按钮. Whether to display the left and right toggle buttons.
  showIndicators: true # 是否显示指示器. # Whether to display the indicators
  autoLoop: true # 是否自动轮播. Whether it is automatically rotated.
  duration: 500 # 切换延迟时间. Switching delay time.
  intervalTime: 5000 # 自动切换下一张的间隔时间. Automatically switch the interval of the next one.
  useConfig: false # 是否使用配置文件, 在 _data/covers.json 下配置推荐文章, false则使用主题在文章中的配置 cover coverImg
  # useConfig 使用方式: 将主题 hexo-theme-matery/source/_data/covers.json 移动到 my-blog/source/_data/下修改配置即可
```
主题的source下已经没有_data文件了，全局搜索也找不到covers.json的示例文件
还是觉得配json文件会比在文章里写`cover: ture`要更容易管理一点，希望能有官方的示例文件。
