### ISSUE TITLE
建议用滚动代替代码折行

### ISSUE THREAD

**Issue by lvxianchao** [blinkfox/hexo-theme-matery#77]
如题，现在的样式长代码不能滚动，是折行，感觉这样不是很友好，或者能够出一个选项，变成可配置的也好。

![image](https://user-images.githubusercontent.com/22412818/52936045-05631000-3396-11e9-92a5-c93270cbc97e.png)

**Comment by blinkfox** [comment]
你好，`v1.0.1`版本增加了一个代码是否折行的配置项，可以下载使用[最新版](https://github.com/blinkfox/hexo-theme-matery/releases)的主题。

在主题的`_config.yml`中，关闭折行的配置如下：

```yaml
# Whether the code is broken.
# 代码是否折行
code:
  break: false
```
