### ISSUE TITLE
代码块显示异常

### ISSUE THREAD

**Issue by bohr777** [blinkfox/hexo-theme-matery#777]
默认配置下代码块是这样的
![image](https://user-images.githubusercontent.com/56676965/158153893-390f4de1-d4b4-4c39-a29f-ee97d852ea1c.png)
演示站点中代码块是这样的
![image](https://user-images.githubusercontent.com/56676965/158154095-2c44cf78-65f1-4fd3-8e72-6e39a72a745a.png)
是哪里出了问题呢

**Comment by mirrorfire** [comment]
我也遇到了这样的问题，尝试了prism_plugin插件，调config和css的配置，都没有解决...求大佬帮助！@blinkfox @bohr777 @appotry @sukrosono @yuxuanh

**Comment by Sagiri-kawaii01** [comment]
首先执行`npm uninstall hexo-prism-plugin`
然后在根配置文件中**修改**代码高亮配置为：
```yaml
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''
```
最后执行`hexo clean` 和 `hexo server`
