### ISSUE TITLE
Prism代码高亮似乎有问题，好像不起作用，样式文件夹里也找不到Prism.css

### ISSUE THREAD

**Issue by XiaoSenLuo** [blinkfox/hexo-theme-matery#8]
配置 关于 custom_css:的配置是空的

**Comment by XiaoSenLuo** [comment]
我下载了官方的prism.css，然后重命名my.css。好像也不起作用

**Comment by XiaoSenLuo** [comment]
我去看了插件作者的github，很多人都反应不起作用。你能添加Prism.js，prism.css作为代码高亮的插件吗

**Comment by blinkfox** [comment]
@XiaoSenLuo 话说你解决了没，我到也没怎么用过它那个`custom_css`的功能，我在`matery.css`对代码内外边距有做小修改，其他的都是用的`hexo-prism-plugin`的插件的功能，我的代码高亮都是可以的呢

**Comment by liweiwei1419** [comment]
您好，我的代码高亮配置如下：

```
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: false

# 参考资料：https://github.com/blinkfox/hexo-theme-matery/blob/develop/README_CN.md
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'tomorrow'
  line_number: false    # default false
```



但显示是这样的：

![jietu20190127-014838 2x](https://user-images.githubusercontent.com/7555554/51790890-00b39d80-21d6-11e9-9829-e043cb5e96f9.jpg)

不知道是我哪里配置错了呢？谢谢。
