### ISSUE TITLE
二级菜单下的相册部署在本地/gitee、github/vercel产生的目录结构不同

### ISSUE THREAD

**Issue by i-abc** [blinkfox/hexo-theme-matery#816]
# 二级菜单下的相册部署在本地/gitee正常，然而部署在github/vercel出错。
## 一、部署在github/vercel：
1. [ https://i-abc.github.io/galleries ](https://i-abc.github.io/galleries)：
![github1](https://user-images.githubusercontent.com/104631897/168407138-6898195e-e7b2-495c-b29c-4400e5c1ebe9.png)

2. 点击，本应该是跳转到[ https://i-abc.github.io/galleries/2022 ](https://i-abc.github.io/galleries/2022)的，结果跳转到了[ https://i-abc.github.io/2022 ](https://i-abc.github.io/2022)：
![github2](https://user-images.githubusercontent.com/104631897/168407247-7b2544a2-4f68-4336-98d9-b854142e59df.png)

3. 直接输入[ https://i-abc.github.io/galleries/2022 ](https://i-abc.github.io/galleries/2022)则正常：
![github3](https://user-images.githubusercontent.com/104631897/168407278-4f1ebc7a-129c-45a2-ae63-909cc7974521.png)

## 二、部署在本地/gitee时正常，无以上跳转错误
[ https://i-abc.gitee.io/galleries/ ](https://i-abc.gitee.io/galleries/)：
![gitee1](https://user-images.githubusercontent.com/104631897/168407342-13a2596e-5ea8-4318-b086-0867fad71af6.png)

![gitee2](https://user-images.githubusercontent.com/104631897/168407345-7e050121-a321-4401-8cdd-a30e5d1dcef0.png)

## 三、补充
这个相册搭建我按Yafine大佬的教程来的：[修改 matery 原有主题相册](https://yafine-blog.cn/posts/3b98.html)。

**Comment by i-abc** [comment]
目前猜测是github/vercel部署后的[ https://i-abc.github.io/galleries ](https://i-abc.github.io/galleries)缺少了/，如果把/加上 [ https://i-abc.github.io/galleries/ ](https://i-abc.github.io/galleries/)则正常了，但我不知道该如何修改。

我也看了#133，还是搞不懂，我其他的目录都正常，只有二级菜单下相册这个出了问题。
这是我的设置：
```
url: https://seeseeme.cn/
root: /
repo: 
   gitee:  https://gitee.com/i-abc/i-abc.git
   github: https://github.com/i-abc/i-abc.github.io.git
```

**Comment by i-abc** [comment]
我改了下主题设置的_config.yml，正常了。
把
```
  # 二级菜单写法如下
  Medias:
    icon: fas fa-list
    children:
      - name: 相册
        url: /galleries
        icon: fas fa-image
```
改为了：
```
 url: /galleries/
```
这下github/vercel/本地/gitee都正常了。
我也是瞎试的，没想到成功了，但不知道正确方法是不是这样，还是等作者看看确定了再close。
