### ISSUE TITLE
音乐播放无法使用

### ISSUE THREAD

**Issue by shilizhuang** [blinkfox/hexo-theme-matery#836]
![image](https://user-images.githubusercontent.com/101449379/180592653-bc0b18eb-441d-4d4f-9541-27a01ed71297.png)
如图，
music:
  enable: true
  title: #非吸底模式有效
    enable: true
    show: 听听音乐
  autoHide: true    # hide automaticaly
  server: tencent   # netease, tencent, kugou, xiami, baidu
  type: playlist    # require song, playlist, album, search, artist
  id: 2362260213    # song id / playlist id / album id / search keyword
  fixed: true       # 开启吸底模式
  autoplay: false   # 是否自动播放
  theme: '#42b983'
  loop: 'all'       # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'random'   # 音频循环顺序, 可选值: 'list', 'random'
  preload: 'auto'   # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7       # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: true  # 列表默认折叠
  hideLrc: true     # 隐藏歌词
该配的我都配置了，但是没有效果啊

**Comment by UniStart2** [comment]
你试试把music下的autoplay从false改成true，我改了之后就能看到播放器了。
然后你在命令行输入 hexo cl && hexo g && hexo s在看看行不行。

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35069045/183287542-96b7b842-99d1-472f-a4ca-6ef97d590983.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35069045/183287575-42041ad9-fd04-4447-a999-4712341a8fad.png">

**Comment by UniStart2** [comment]
不过我本地看可以用，但是部署到githubpage之后貌似音乐就播放失效了，这我也不知道为啥😭

**Comment by limitlm** [comment]
> 不过我本地看可以用，但是部署到githubpage之后貌似音乐就播放失效了，这我也不知道为啥😭

markdown插入音乐，推荐安装hexo-tag-mmedia插件
然后将以下代码放在markdown文件的正文部分，具体参数可按照教程修改
{% mmedia "meting" "server=netease" "type=song" "id=30431367" "autoplay=true" %}

**Comment by 2319048236** [comment]
我也想知道

**Comment by UniStart2** [comment]
## 下面是我博客关于音乐部分的配置，同时需要安装hexo插件[hexo-tag-aplayer](https://github.com/MoePlayer/hexo-tag-aplayer)
```yml
# Whether to display the musics.
# 是否在首页显示音乐.
music:
  enable: false
  title: #非吸底模式有效
    enable: true
    show: 听听音乐
  autoHide: true # hide automaticaly
  server: kugou #require music platform: netease, tencent, kugou, xiami, baidu
  type: playlist #require song, playlist, album, search, artist
  id: 3427965 #require song id / playlist id / album id / search keyword
  fixed: true # 开启吸底模式
  autoplay: true # 是否自动播放
  theme: "#42b983"
  loop: "all" # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: "list" # 音频循环顺序, 可选值: 'list', 'random'
  preload: "auto" # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7 # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: true # 列表默认折叠
  hideLrc: true # 隐藏歌词

# Whether to display the musics.
# 单独的音乐页面.
musics:
  enable: true
  title: #非吸底模式有效
    enable: true
    show: 听听音乐
  server: netease #require music platform: netease, tencent, kugou, xiami, baidu
  type: playlist #require song, playlist, album, search, artist
  id: 330695641 #require song id / playlist id / album id / search keyword
  fixed: false # 开启吸底模式
  autoplay: true # 是否自动播放
  theme: "#42b983"
  loop: "all" # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: "random" # 音频循环顺序, 可选值: 'list', 'random'
  preload: "auto" # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7 # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: false # 列表默认折叠
  listMaxHeight: "525px" #列表最大高度

# hexo-tag-aplaye配置
aplayer:
  meting: true # 启用 MetingJS
```

## 下面是我在文章的使用
```markdown
{% meting "329925" "netease" "song" "loop:all" "order:one" listfolded %}
```

##  下面是我之前遇到问题时参考的博客
[夜法之书](https://blog.17lai.site/posts/4d8a0b22/#waline)
