### ISSUE TITLE
是否可以隐藏文章右侧目录

### ISSUE THREAD

**Issue by DragonLanQAQ** [blinkfox/hexo-theme-matery#850]
有的文章想要全屏展示，右侧目录有点太膈应

**Comment by UniStart2** [comment]
# 是否激活文章 TOC 功能，并配置TOC支持选中哪些标题类型，这是全局配置。
# 可以在某篇文章的 Front-matter 中再加上`toc: false`，使该篇文章关闭TOC目录功能
toc:
  enable: true
  heading: h2, h3, h4
  collapseDepth: 0 # 目录默认展开层级
  showToggleBtn: true # 是否显示切换TOC目录展开收缩的按钮
  
配置文件中已经说的很明确了

**Comment by UniStart2** [comment]
```yml 
# 是否激活文章 TOC 功能，并配置TOC支持选中哪些标题类型，这是全局配置。
# 可以在某篇文章的 Front-matter 中再加上`toc: false`，使该篇文章关闭TOC目录功能
toc:
  enable: true
  heading: h2, h3, h4
  collapseDepth: 0 # 目录默认展开层级
  showToggleBtn: true # 是否显示切换TOC目录展开收缩的按钮
```

你把上面的enable改成false，就全局文章都没目录了；如果你想指定文章不开启目录，在文章的front-matter中指定toc: false就好了
