### ISSUE TITLE
移动端背景图适配问题

### ISSUE THREAD

**Issue by cs-moushuai** [blinkfox/hexo-theme-matery#852]
在 config.yml 中有下面一行配置
```yml
# 网站背景图
background:
  enable: true
  url: "https://cdn.jsdelivr.net/gh/Tokisaki-Galaxy/res/site/medias/background.jpg"
```
在移动端图片由于比例问题，表现不良好
建议做一个移动端不显示背景图的功能
