### ISSUE TITLE
waline评论深色模式

### ISSUE THREAD

**Issue by pengsec** [blinkfox/hexo-theme-matery#880]
我很想问一下，waline评在深色模式下能不能也渲染成深色，还是说无法实现，大佬能回答一下，谢谢。
![image](https://user-images.githubusercontent.com/120392682/221479486-17c317c0-fbc8-45db-91c4-c79f08ac31d6.png)

**Comment by appotry** [comment]
如果是matery dev 分支的话，修改方式如下

```
waline:
  enable: true
  # Waline 服务端部署参考 https://waline.js.org/guide/server/intro.html 客户端和服务端版本需一致
  # 下面是一个例子，请替换成自己的服务端
  serverURL: 'https://waline.xxx.xxx' 
  avatar: 'mp' # Gravatar style : ''/mp/identicon/monsterid/wavatar/retro/hide
  path: "window.location.pathname.replace(/\/$/,'')"
  # visitor: true   # 文章访问量统计  v1 更名为 pageview
  lang: zh-CN     # 语言，默认zh-CN
  dark: 'body[class="DarkMode"]'      # 黑暗模式适配

```

效果可以参见个人[blog](https://blog.17lai.site/posts/40300608/)
