### ISSUE TITLE
verifyPassword function can be bypass

### ISSUE THREAD

**Issue by xzajyjs** [blinkfox/hexo-theme-matery#897]
- affected version: v2.0.0
---
# config
```yaml
# _config.yml
# The password verification feature of read post. To use this feature,
# activate the configuration item and write the 'password' key and Cipher in the post's Front-matter.
# Note: In order to ensure that the original password will not be leaked to the web page,
# the password of the article must be encrypted by 'SHA256' so that it will not be cracked.
# 阅读文章的密码验证功能，如要使用此功能请激活该配置项，并在对应文章的Front-matter中写上'password'的键和加密后的密文即可.
# 请注意：为了保证密码原文不会被泄露到网页中，文章的密码必须是通过'SHA256'加密的，这样就不会被破解.
verifyPassword:
  enable: true
  promptMessage: 请输入访问本文章的密码
  errorMessage: 密码错误，将返回主页！
```
![test1](https://github.com/blinkfox/hexo-theme-matery/assets/25580455/f7f03106-5efe-457a-90d7-8014b8bba28c)

---

# bypass
```
curl http://localhost:4000/2023/11/03/test/ > haha.html
```
![test3](https://github.com/blinkfox/hexo-theme-matery/assets/25580455/f7be9caf-a316-49be-8e49-c77ba97258f0)
