### ISSUE TITLE
hexo7.1.1代码显示问题

### ISSUE THREAD

**Issue by YiJieLiuHub** [blinkfox/hexo-theme-matery#910]
![image](https://github.com/blinkfox/hexo-theme-matery/assets/86114492/9df454dc-e48e-4c4d-bff9-622913e147fd)
配置如下：
```yaml
syntax_highlighter: prismjs
highlight:
  auto_detect: false
  line_number: true
  line_threshold: 0
  tab_replace: ''
  exclude_languages:
    - example
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ''
```

**Comment by YiJieLiuHub** [comment]
以上问题已经解决，但是渲染不了Vue代码
![image](https://github.com/blinkfox/hexo-theme-matery/assets/86114492/695665c7-edd2-4aca-b601-531779dad274)

**Comment by yanhuacuo** [comment]
目前看，只能降级

**Comment by yanhuacuo** [comment]
[prism.zip](https://github.com/blinkfox/hexo-theme-matery/files/14183508/prism.zip)
## 解决办法

## 博客根目录中使用新参数

根目录的 `_config.yaml` 中：

```yaml
syntax_highlighter: prismjs
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''
```
## 添加  prismjs.css

在目录　`hexo-theme-matery\source\libs\prism`　下，添加：prism.css

- prism.css 下载地址:　https://prismjs.com/download.html

分享：

[prism.zip](https://github.com/blinkfox/hexo-theme-matery/files/14183512/prism.zip)
