### ISSUE TITLE
请问代码块右侧滚动条怎么隐藏

### ISSUE THREAD

**Issue by YeQiuO** [blinkfox/hexo-theme-matery#917]
![image](https://github.com/blinkfox/hexo-theme-matery/assets/45990941/87cb0449-1500-4593-83a8-c7e2f3d48316)

代码块设置如下
```yaml
syntax_highlighter: prismjs
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''
```
