### ISSUE TITLE
代码块里的函数名变大了，这个怎么解决

### ISSUE THREAD

**Issue by vb3328998** [blinkfox/hexo-theme-matery#919]
![image](https://github.com/blinkfox/hexo-theme-matery/assets/40584745/2837a106-a5d3-435a-989a-d94b07bf9863)
函数名变大了，而且还有3个点点

**Comment by MilkTeaAddicted** [comment]
你解决了吗。之前的框架没有这个问题，但是新版本出现异常了

**Comment by vb3328998** [comment]
> 你解决了吗。之前的框架没有这个问题，但是新版本出现异常了

是的，改了主题的config就可以了

code:
  lang: false # 代码块是否显示名称
  copy: true # 代码块是否可复制
  shrink: true # 代码块是否可以收缩
  break: true # 代码是否折行

**Comment by q779** [comment]
我是改的根目录的config，hexo 7.0.0以上 好像把代码高亮的东西改了

```
syntax_highlighter: prismjs # or highlight.js
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''
```

另外要确保你的主题是最新的，我的就是几年前的那个版本，然后手动改了好多文件才搞好的。qwq
