### ISSUE TITLE
Posts card : Pictures are stretched

### ISSUE THREAD

**Issue by Tilix4** [blinkfox/hexo-theme-matery#92]
If the display ratio changes, pictures are stretched, which makes them look bad, is it possible to crop them and keeping them centered ?

![BugWebsite](https://user-images.githubusercontent.com/22875539/54614983-9c86ba80-4a5d-11e9-978d-8b6b7ca3b7d3.PNG)

**Comment by blinkfox** [comment]
I don't have a good way to adapt to all ratios of screens.

**Comment by HarborZeng** [comment]
@blinkfox I think I have a good idea.

let's say we have a twisted image of planet here:
![image](https://user-images.githubusercontent.com/8568937/55684188-f999d000-597a-11e9-8e9c-310891675d64.png)

add this line `object-fit: cover;` to `article .card-image img`, and it will be perfect

![image](https://user-images.githubusercontent.com/8568937/55684207-3a91e480-597b-11e9-871d-a6138aace782.png)

code is pasted below:
```css
article .card-image img {
    height: 220px;
    border-radius: 0.3rem;
    opacity: .7;
    object-fit: cover;
}
```
