### ISSUE TITLE
valine评论插件排版出现问题

### ISSUE THREAD

**Issue by wyx1818** [blinkfox/hexo-theme-matery#97]
![image](https://user-images.githubusercontent.com/31715036/55670175-af015080-58b3-11e9-9527-d61975dcdda0.png)
第一个评论会位移，更新valine版本也没有改善，其他主题无此问题
参见https://zuiyu1818.cn/posts/Hac_Clover.html

**Comment by HarborZeng** [comment]
@wyx1818 我测试了下确实是这样的，原因是因为上面的“2评论”显示条`display`属性有问题，当设为`block`时，因为他内部又嵌了一个`div`，所有会导致父div认为自己的高度和宽度为0（因为`padding: 5px`才让他有了10px的高度），10px的高度远远不够，导致首条评论的头像被挤到右边了（头像的float: left），解决方法就是，要么:

```css
div .vinfo {
    display: flex或grid;
}
```

要么：

```css
div .vcount {
    display: contents;
}
```

这两种办法都是让那个父div有宽高，把宽高撑起来，让头像换行而不是向左浮动。

这两个css任选一个，放在my.css或matery.css里面应该就可以了。

![image](https://user-images.githubusercontent.com/8568937/55677398-0259ba00-5919-11e9-8677-c1fb70ef6a9d.png)
