### ISSUE TITLE
文章摘要的问题

### ISSUE THREAD

**Issue by Riroaki** [blinkfox/hexo-theme-matery#99]
@Loveslife 这个功能我已经加上了，更新最新的主题即可。你可以在文章的`Front-matter`中自定义文章内容的摘要`summary`，写法如下：

```yaml
---
title: typora-vue-theme主题介绍
date: 2018-09-07 09:25:00
img: /source/images/xxx.jpg
summary: 这是你自定义的文章摘要内容，如果这个属性有值，文章卡片摘要就显示这段文字，否则程序会自动截取文章的部分内容作为摘要
categories: Markdown
tags:
  - Typora
  - Markdown
---
```

_Originally posted by @blinkfox in https://github.com/blinkfox/hexo-theme-matery/issues/51#issuecomment-456696129_

你好，请问有没有办法摘要到出现标签之前的内容（也就是截取全文，但是遇到这个标签就停止）?
我了解到像yilia、next这些主题都有支持按照这一标签截取的特性，
个人觉得每篇文章都写summary不是十分方便。
